In [2]:
import pandas as pd
import numpy as np
from functools import reduce

## Выгружаем данные

In [4]:
df_births = pd.read_csv(r'G:\Демография\1. births.filtered\births.csv')
df_migration = pd.read_csv(r"G:\Демография\1.1 annual-net-migration.filtered\annual-net-migration.csv")
df_deaths = pd.read_csv(r"G:\Демография\2. deaths.filtered\deaths.csv")
df_infant_deaths = pd.read_csv(r"G:\Демография\2.1 number-of-infant-deaths.filtered\number-of-infant-deaths.csv")
df_child_deaths = pd.read_csv(r"G:\Демография\2.2 number-of-child-deaths.filtered\number-of-child-deaths.csv")
df_population_density = pd.read_csv(r"G:\Демография\5. population-density.filtered\population-density.csv")
df_population = pd.read_csv(r"G:\Демография\6. population\population.csv")
df_sex_ration = pd.read_csv(r"G:\Демография\7. sex-ratio.filtered\sex-ratio.csv")
df_fertility_rate = pd.read_csv(r"G:\Демография\1.2 fertility-rate-children-per-woman\fertility-rate-children-per-woman.csv")

df_world_gdp_ppp = pd.read_csv(r"G:\Демография\gdp-penn-world-table\gdp-penn-world-table.csv")
df_world_gdp_constant = pd.read_csv(r"G:\Демография\gdp-worldbank-constant-usd\gdp-worldbank-constant-usd.csv")
df_military_of_gdp = pd.read_csv(r"G:\Демография\4. military-spending-as-a-share-of-gdp-sipri\military-spending-as-a-share-of-gdp-sipri.csv")
df_country_literacy = pd.read_csv(r"G:\Демография\3. cross-country-literacy-rates\cross-country-literacy-rates.csv")

In [5]:
df_world_gdp_constant.head()

        Entity Code  Year         GDP
0  Afghanistan  AFG  2000  6206547590
1  Afghanistan  AFG  2001  5621147630
2  Afghanistan  AFG  2002  7228795918
3  Afghanistan  AFG  2003  7867263256
4  Afghanistan  AFG  2004  7978515641

In [6]:
df_world_gdp_ppp = df_world_gdp_ppp.rename(columns={'GDP': 'GDP_PPP'})
df_world_gdp_constant = df_world_gdp_constant.rename(columns={'GDP': 'GDP_Constant'})

In [7]:
data_frames = [
    df_births, 
    df_migration, 
    df_deaths, 
    df_infant_deaths, 
    df_child_deaths, 
    df_population_density,
    df_population,
    df_sex_ration,
    df_fertility_rate,
    df_world_gdp_ppp,
    df_world_gdp_constant,
    df_military_of_gdp,
    df_country_literacy
]

## Соединяем таблицы с одинаковыми столбцами и заполняем пропуски

In [9]:
df_merged = reduce(lambda left, right: pd.merge(left, right, on=['Entity', 'Code', 'Year'], how='outer'), data_frames)

In [10]:
## Метод "Последнего известного значения" (Forward Fill)

df_merged = df_merged.sort_values(['Entity', 'Year'])

columns_to_fix = ['GDP_PPP','GDP_Constant','Literacy rate', 'Military expenditure (% of GDP)']
df_merged[columns_to_fix] = df_merged.groupby('Entity')[columns_to_fix].ffill()

In [11]:
df_merged = df_merged.rename(columns={'all years': 'Population'})

In [12]:
df_merged.head()

,Entity,Code,Year,"Births, total","Net migration, total","Number of deaths, total","Number of deaths, at birth","Number of deaths, ages 0-4","Population density, total",Population,"Sex ratio, total","Fertility rate, total",GDP_PPP,GDP_Constant,Military expenditure (% of GDP),World region according to OWID,Literacy rate
0,Afghanistan,AFG,1950,383985.0,6161.0,290972.0,109220.0,160791.0,11.976,7776180.0,112.618350,7.248,NaN,NaN,NaN,NaN,3.0
1,Afghanistan,AFG,1951,391002.0,4903.0,288752.0,107971.0,158566.0,12.135,7879343.0,112.082695,7.260,NaN,NaN,NaN,NaN,3.0
2,Afghanistan,AFG,1952,397663.0,145.0,288059.0,108140.0,157832.0,12.302,7987784.0,111.549510,7.260,NaN,NaN,NaN,NaN,3.0
3,Afghanistan,AFG,1953,404666.0,-8867.0,287712.0,108248.0,157554.0,12.470,8096703.0,111.028630,7.266,NaN,NaN,NaN,NaN,3.0
4,Afghanistan,AFG,1954,410428.0,-6837.0,289189.0,108241.0,157723.0,12.641,8207954.0,110.527370,7.254,NaN,NaN,NaN,NaN,3.0

## Определяем и создаем Code_Types

In [14]:
unique_code = df_merged['Code'].unique()

In [15]:
unique_code

array(['AFG', 'OWID_AFR', 'UN_AFR', nan, 'ALB', 'DZA', 'ASM', 'AND',
       'AGO', 'AIA', 'ATG', 'ARG', 'ARM', 'ABW', 'OWID_ASI', 'UN_ASI',
       'AUS', 'AUT', 'AZE', 'BHS', 'BHR', 'BGD', 'BRB', 'BLR', 'BEL',
       'BLZ', 'BEN', 'BMU', 'BTN', 'BOL', 'BES', 'BIH', 'BWA', 'BRA',
       'VGB', 'BRN', 'BGR', 'BFA', 'BDI', 'KHM', 'CMR', 'CAN', 'CPV',
       'CYM', 'CAF', 'TCD', 'OWID_CIS', 'CHL', 'CHN', 'CCK', 'COL', 'COM',
       'COG', 'COK', 'CRI', 'CIV', 'HRV', 'CUB', 'CUW', 'CYP', 'CZE',
       'OWID_CZS', 'COD', 'DNK', 'DJI', 'DMA', 'DOM', 'WB_EAP', 'TLS',
       'ECU', 'EGY', 'SLV', 'GNQ', 'ERI', 'EST', 'SWZ', 'ETH', 'OWID_EUR',
       'UN_EUR', 'WB_ECA', 'OWID_EU27', 'FLK', 'FRO', 'FJI', 'FIN', 'FRA',
       'GUF', 'PYF', 'GAB', 'GMB', 'GEO', 'DEU', 'GHA', 'GIB', 'GRC',
       'GRL', 'GRD', 'GLP', 'GUM', 'GTM', 'GGY', 'GIN', 'GNB', 'GUY',
       'HTI', 'OWID_HIC', 'HND', 'HKG', 'HUN', 'ISL', 'IND', 'IDN', 'IRN',
       'IRQ', 'IRL', 'IMN', 'ISR', 'ITA', 'JAM', 'JPN', 'JEY', 'JOR',
       'KAZ', 'KEN', 'KIR', 'OWID_KOS', 'KWT', 'KGZ', 'LAO', 'WB_LAC',
       'UN_LAC', 'LVA', 'LBN', 'LSO', 'LBR', 'LBY', 'LIE', 'LTU',
       'OWID_LIC', 'OWID_LMC', 'LUX', 'MAC', 'MDG', 'MWI', 'MYS', 'MDV',
       'MLI', 'MLT', 'MHL', 'MTQ', 'MRT', 'MUS', 'MYT', 'MEX', 'FSM',
       'WB_MENAP', 'MDA', 'MCO', 'MNG', 'MNE', 'MSR', 'MAR', 'MOZ', 'MMR',
       'NAM', 'NRU', 'NPL', 'NLD', 'ANT', 'NCL', 'NZL', 'NIC', 'NER',
       'NGA', 'NIU', 'NFK', 'OWID_NAM', 'WB_NA', 'PRK', 'MKD', 'UN_NAM',
       'MNP', 'NOR', 'OWID_OCE', 'UN_OCE', 'OMN', 'PAK', 'PLW', 'PSE',
       'PAN', 'PNG', 'PRY', 'PER', 'PHL', 'POL', 'PRT', 'PRI', 'QAT',
       'REU', 'ROU', 'RUS', 'RWA', 'BLM', 'SHN', 'KNA', 'LCA', 'MAF',
       'SPM', 'VCT', 'WSM', 'SMR', 'STP', 'SAU', 'SEN', 'SRB', 'SYC',
       'SLE', 'SGP', 'SXM', 'SVK', 'SVN', 'SLB', 'SOM', 'OWID_SML', 'ZAF',
       'OWID_SAM', 'WB_SA', 'KOR', 'SSD', 'ESP', 'LKA', 'WB_SSA', 'SDN',
       'SUR', 'SWE', 'CHE', 'SYR', 'TWN', 'TJK', 'TZA', 'THA', 'TGO',
       'TKL', 'TON', 'TTO', 'TUN', 'TUR', 'TKM', 'TCA', 'TUV', 'OWID_USS',
       'UGA', 'UKR', 'ARE', 'GBR', 'USA', 'VIR', 'OWID_UMC', 'URY', 'UZB',
       'VUT', 'VAT', 'VEN', 'VNM', 'WLF', 'ESH', 'OWID_WRL', 'YEM',
       'OWID_YGS', 'ZMB', 'OWID_ZAN', 'ZWE'], dtype=object)

In [16]:
len(unique_code)

272

In [17]:
def classify_code(code):
    c = str(code)
    if c == 'OWID_WRL': # 1. Весь мир
        return 'World'
    elif c in ['OWID_HIC', 'OWID_LIC', 'OWID_LMC', 'OWID_UMC']: # 2. По ВВП 
        return 'Income Group'
    elif c.startswith('OWID_') and c not in ['OWID_KOS']: # 3. Континенты по версии OWID
        return 'Continent (OWID)'
    elif c.startswith('UN_'): # 4. Континенты по версии ООН
        return 'Region (UN)'
    elif len(c) == 3 and c.isupper(): # 5. Страны
        return 'Country'
    elif c == 'OWID_KOS':
        return 'Country' # Косово считаем как страну
    else: # Другое
        return 'Territory/Other'

### Список Income Group: 
- OWID_HIC (High Income — Высокий доход)
- OWID_UMC (Upper Middle Income — Выше среднего)
- OWID_LMC (Lower Middle Income — Ниже среднего)
- OWID_LIC (Low Income — Низкий доход)

In [19]:
df_merged['Code_Type'] = df_merged['Code'].apply(classify_code)

In [20]:
df_merged.head()

,Entity,Code,Year,"Births, total","Net migration, total","Number of deaths, total","Number of deaths, at birth","Number of deaths, ages 0-4","Population density, total",Population,"Sex ratio, total","Fertility rate, total",GDP_PPP,GDP_Constant,Military expenditure (% of GDP),World region according to OWID,Literacy rate,Code_Type
0,Afghanistan,AFG,1950,383985.0,6161.0,290972.0,109220.0,160791.0,11.976,7776180.0,112.618350,7.248,NaN,NaN,NaN,NaN,3.0,Country
1,Afghanistan,AFG,1951,391002.0,4903.0,288752.0,107971.0,158566.0,12.135,7879343.0,112.082695,7.260,NaN,NaN,NaN,NaN,3.0,Country
2,Afghanistan,AFG,1952,397663.0,145.0,288059.0,108140.0,157832.0,12.302,7987784.0,111.549510,7.260,NaN,NaN,NaN,NaN,3.0,Country
3,Afghanistan,AFG,1953,404666.0,-8867.0,287712.0,108248.0,157554.0,12.470,8096703.0,111.028630,7.266,NaN,NaN,NaN,NaN,3.0,Country
4,Afghanistan,AFG,1954,410428.0,-6837.0,289189.0,108241.0,157723.0,12.641,8207954.0,110.527370,7.254,NaN,NaN,NaN,NaN,3.0,Country

### Определяем страны, которые не публикуют расходы на военку

In [22]:
df_military_of_gdp.head()

,Entity,Code,Year,Military expenditure (% of GDP),World region according to OWID
0,Afghanistan,AFG,1970,1.629606,Asia
1,Afghanistan,AFG,1973,1.868910,Asia
2,Afghanistan,AFG,1974,1.610825,Asia
3,Afghanistan,AFG,1975,1.722066,Asia
4,Afghanistan,AFG,1976,2.046087,Asia

In [23]:
region_map = df_military_of_gdp[['Entity', 'World region according to OWID']].drop_duplicates().dropna()

In [24]:
region_map.info

<bound method DataFrame.info of            Entity World region according to OWID
0     Afghanistan                           Asia
24        Albania                         Europe
69        Algeria                         Africa
133        Angola                         Africa
173     Argentina                  South America
...           ...                            ...
8034    Venezuela                  South America
8103      Vietnam                           Asia
8127        Yemen                           Asia
8152       Zambia                         Africa
8188     Zimbabwe                         Africa

[165 rows x 2 columns]>

In [25]:
all_countries = set(df_merged[df_merged['Code_Type'] == 'Country']['Entity'].unique())

military_entities = set(df_military_of_gdp['Entity'].unique())

missing_countries = sorted(list(all_countries - military_entities))

In [26]:
len(missing_countries)

75

In [27]:
missing_countries

['American Samoa',
 'Andorra',
 'Anguilla',
 'Antigua and Barbuda',
 'Aruba',
 'Bahamas',
 'Barbados',
 'Bermuda',
 'Bhutan',
 'Bonaire Sint Eustatius and Saba',
 'British Virgin Islands',
 'Cayman Islands',
 'Cocos Islands',
 'Comoros',
 'Cook Islands',
 'Costa Rica',
 'Curacao',
 'Dominica',
 'Falkland Islands',
 'Faroe Islands',
 'French Guiana',
 'French Polynesia',
 'Gibraltar',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guernsey',
 'Hong Kong',
 'Iceland',
 'Isle of Man',
 'Jersey',
 'Kiribati',
 'Liechtenstein',
 'Macao',
 'Maldives',
 'Marshall Islands',
 'Martinique',
 'Mayotte',
 'Micronesia (country)',
 'Monaco',
 'Montserrat',
 'Nauru',
 'Netherlands Antilles',
 'New Caledonia',
 'Niue',
 'Norfolk Island',
 'North Korea',
 'Northern Mariana Islands',
 'Palau',
 'Palestine',
 'Puerto Rico',
 'Reunion',
 'Saint Barthelemy',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin (French part)',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Sint Maarten (Dutch part)',
 'Solomon Islands',
 'Suriname',
 'Tokelau',
 'Tonga',
 'Turks and Caicos Islands',
 'Tuvalu',
 'United States Virgin Islands',
 'Vanuatu',
 'Vatican',
 'Wallis and Futuna',
 'Western Sahara']

### Создаем столбец World_Region (Части света)

In [29]:
full_region_map = dict(zip(region_map['Entity'], region_map['World region according to OWID']))

In [30]:
manual_regions = {
    # Европа
    'Andorra': 'Europe', 'Faroe Islands': 'Europe', 'Gibraltar': 'Europe', 'Guernsey': 'Europe', 
    'Iceland': 'Europe', 'Isle of Man': 'Europe', 'Jersey': 'Europe', 'Liechtenstein': 'Europe', 
    'Monaco': 'Europe', 'San Marino': 'Europe', 'Vatican': 'Europe',
    
    # Азия
    'Bhutan': 'Asia', 'Hong Kong': 'Asia', 'Macao': 'Asia', 'Maldives': 'Asia', 
    'North Korea': 'Asia', 'Palestine': 'Asia',
    
    # Северная Америка (включая Карибы)
    'Anguilla': 'North America', 'Antigua and Barbuda': 'North America', 'Aruba': 'North America', 
    'Bahamas': 'North America', 'Barbados': 'North America', 'Bermuda': 'North America', 
    'British Virgin Islands': 'North America', 'Cayman Islands': 'North America', 
    'Costa Rica': 'North America', 'Dominica': 'North America', 'Greenland': 'North America', 
    'Grenada': 'North America', 'Puerto Rico': 'North America', 'Saint Kitts and Nevis': 'North America', 
    'Saint Lucia': 'North America', 'Saint Vincent and the Grenadines': 'North America', 
    'Turks and Caicos Islands': 'North America', 'United States Virgin Islands': 'North America',
    
    # Океания
    'American Samoa': 'Oceania', 'Cook Islands': 'Oceania', 'French Polynesia': 'Oceania', 
    'Guam': 'Oceania', 'Kiribati': 'Oceania', 'Marshall Islands': 'Oceania', 'Nauru': 'Oceania', 
    'New Caledonia': 'Oceania', 'Palau': 'Oceania', 'Samoa': 'Oceania', 'Solomon Islands': 'Oceania', 
    'Tonga': 'Oceania', 'Tuvalu': 'Oceania', 'Vanuatu': 'Oceania',
    
    # Южная Америка
    'Suriname': 'South America', 'French Guiana': 'South America'
}

In [31]:
full_region_map.update(manual_regions)

In [32]:
df_merged['World_Region'] = df_merged['Entity'].map(full_region_map)

### Проверка стран в выборке

In [34]:
countries_list = sorted(df_merged[df_merged['Code_Type'] == 'Country']['Entity'].unique())

In [35]:
len(countries_list)

240

In [36]:
countries_list

['Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bonaire Sint Eustatius and Saba',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Cocos Islands',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Czechia',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'East Timor',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Falkland Islands',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macao',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Micronesia (country)',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'Netherlands Antilles',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'Norfolk Island',
 'North Korea',
 'North Macedonia',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Reunion',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Barthelemy',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin (French part)',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten (Dutch part)',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Tokelau',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'United States Virgin Islands',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican',
 'Venezuela',
 'Vietnam',
 'Wallis and Futuna',
 'Western Sahara',
 'Yemen',
 'Zambia',
 'Zimbabwe']

### Создаем метрики и группы

In [38]:
latest_population = df_merged[df_merged['Year'] == 2021][['Entity', 'Population']]

def classify_population(population):
    if population > 500000000: return '1. Global Giants (>0.5В)'
    elif population > 250000000: return '2. Super Large (250M-500M)'
    elif population > 100000000:  return '3. Large (100M-250M)'
    elif population > 50000000:  return '4. Medium (50M-100M)'
    elif population > 20000000:  return '5. Low Medium (20M-50M)'
    elif population > 5000000:  return '6. Small (5M-20M)'
    else: return '7. Really Small (<5M)'

latest_population['Population_Type'] = latest_population['Population'].apply(classify_population)

df_merged = pd.merge(df_merged, latest_population[['Entity', 'Population_Type']], on='Entity', how='left')

In [39]:
df_merged['Population_Net_Change'] = (
    df_merged['Births, total'] - 
    df_merged['Number of deaths, total'] + 
    df_merged['Net migration, total']
)

In [40]:
df_merged['GDP_Per_Capita_PPP'] = df_merged['GDP_PPP'] / df_merged['Population']
df_merged['GDP_Per_Capita_Constant'] = df_merged['GDP_Constant'] / df_merged['Population']
df_merged['Price_Level_Ratio'] = df_merged['GDP_PPP'] / df_merged['GDP_Constant']

target_year = 2023
df_target = df_merged[df_merged['Year'] == target_year].copy()

labels = ['Низкий', 'Ниже среднего', 'Выше среднего', 'Высокий']
df_target['GDP_Capita_Group_PPP_Static'] = pd.qcut(
    df_target['GDP_Per_Capita_PPP'], 4, labels=labels
).astype(object)

group_mapping = df_target.set_index('Entity')['GDP_Capita_Group_PPP_Static'].to_dict()

df_merged['GDP_Capita_Group_PPP'] = df_merged['Entity'].map(group_mapping)

df_merged['GDP_Capita_Group_PPP'] = df_merged['GDP_Capita_Group_PPP'].fillna('Нет данных')

final_labels = ['Низкий', 'Ниже среднего', 'Выше среднего', 'Высокий', 'Нет данных']
df_merged['GDP_Capita_Group_PPP'] = pd.Categorical(
    df_merged['GDP_Capita_Group_PPP'], 
    categories=final_labels, 
    ordered=True
)

In [41]:
print(df_merged[df_merged['Year'] == 2021]['GDP_Capita_Group_PPP'].value_counts())

GDP_Capita_Group_PPP
Нет данных       144
Низкий            46
Ниже среднего     46
Выше среднего     46
Высокий           46
Name: count, dtype: int64

### Обработка пропусков

In [43]:
df_merged.isnull().sum()

Entity                                 0
Code                                2903
Year                                   0
Births, total                       3828
Net migration, total                3828
Number of deaths, total             4050
Number of deaths, at birth          4050
Number of deaths, ages 0-4          4050
Population density, total           4272
Population                          3606
Sex ratio, total                    4050
Fertility rate, total               3828
GDP_PPP                            12555
GDP_Constant                        9963
Military expenditure (% of GDP)    14882
World region according to OWID     15492
Literacy rate                       7596
Code_Type                              0
World_Region                        7414
Population_Type                       17
Population_Net_Change               5752
GDP_Per_Capita_PPP                 12732
GDP_Per_Capita_Constant            12019
Price_Level_Ratio                  13913
GDP_Capita_Group_PPP                   0
dtype: int64

In [44]:
df_merged.shape

(23734, 25)

In [45]:
df_final = df_merged.copy()

In [46]:
df_final['Code'] = df_final['Code'].fillna('N/A')
df_final['World_Region'] = df_final['World_Region'].fillna('Other/Aggregates')

In [47]:
mask = df_final['Population_Net_Change'].isna() & df_final['Births, total'].notna() & df_final['Number of deaths, total'].notna()
df_final.loc[mask, 'Population_Net_Change'] = (
    df_final['Births, total'] - 
    df_final['Number of deaths, total'] + 
    df_final['Net migration, total'].fillna(0)
)

### Дорабатываем и выгружаем df

In [49]:
cols_to_fix = [
    'Births, total', 'Net migration, total', 'Number of deaths, total', 
    'Number of deaths, at birth', 'Number of deaths, ages 0-4', 
    'Population density, total', 'Population',
    'Sex ratio, total', 'Fertility rate, total',
    'GDP_PPP', 'GDP_Constant',
    'Military expenditure (% of GDP)', 'Literacy rate',
    'Population_Net_Change','Price_Level_Ratio'
]

for col in cols_to_fix:
    df_final[col] = pd.to_numeric(df_final[col], errors='coerce')

In [50]:
df_final.isnull().sum()

Entity                                 0
Code                                   0
Year                                   0
Births, total                       3828
Net migration, total                3828
Number of deaths, total             4050
Number of deaths, at birth          4050
Number of deaths, ages 0-4          4050
Population density, total           4272
Population                          3606
Sex ratio, total                    4050
Fertility rate, total               3828
GDP_PPP                            12555
GDP_Constant                        9963
Military expenditure (% of GDP)    14882
World region according to OWID     15492
Literacy rate                       7596
Code_Type                              0
World_Region                           0
Population_Type                       17
Population_Net_Change               5752
GDP_Per_Capita_PPP                 12732
GDP_Per_Capita_Constant            12019
Price_Level_Ratio                  13913
GDP_Capita_Group_PPP                   0
dtype: int64

In [51]:
df_final.rename(columns={
    'Births, total': 'Births_Total',
    'Net migration, total': 'Net_Migration_Total',
    'Number of deaths, total': 'Deaths_Total',
    'Number of deaths, at birth': 'Deaths_At_Birth',
    'Number of deaths, ages 0-4': 'Deaths_Ages_0_4',
    'Population density, total': 'Population_Density_Total',
    'Sex ratio, total': 'Sex_Ratio_Total',
    'Population, total': 'Population_Total',
    'Fertility rate, total': 'Fertility_Rate_Total'
}, inplace=True)

In [52]:
df_final = df_final[df_final['Code_Type'] == 'Country'].copy()

df_final.drop(columns=['Code_Type'], inplace=True, errors='ignore')
df_final.drop(columns=['World region according to OWID'], inplace=True, errors='ignore')

In [53]:
df_final = df_final[df_final['Year'] >= 1950] 

df_final['Date'] = pd.to_datetime(df_final['Year'], format='%Y')

### Добавим Sub Regions и добавим преобразование в NULL всех GDP без Price_Level_Ratio

In [55]:
df_regions = pd.read_csv(r"G:\Демография\сountries_list.csv")
region_mapping = df_regions.set_index('alpha-3')['sub-region'].to_dict()

df_final['Sub_Region'] = df_final['Code'].map(region_mapping)

In [56]:
condition = df_final['Price_Level_Ratio'].isna()

cols_to_fix = ['GDP_Constant', 'GDP_PPP', 'GDP_Per_Capita_Constant', 'GDP_Per_Capita_PPP']

df_final.loc[condition, cols_to_fix] = np.nan

### Добавим geometry

In [58]:
import geopandas as gpd
import json

In [59]:
gdf = gpd.read_file(r"G:\Демография\ne_110m_admin_0_countries\ne_110m_admin_0_countries.shp")

In [62]:
gdf.to_file(r"G:\Демография\countries_geo.geojson", driver='GeoJSON')

In [66]:
data = pd.read_csv(r"G:\Демография\datalens_geopolygons.csv", sep=';')

ParserError: Error tokenizing data. C error: Expected 170 fields in line 4, saw 171

In [113]:
df_final[df_final['Entity'] == 'Russia'][df_final['Literacy rate']>1]

C:\Users\ilyal\AppData\Local\Temp\ipykernel_12380\2736635271.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_final[df_final['Entity'] == 'Russia'][df_final['Literacy rate']>1]

,Entity,Code,Year,Births_Total,Net_Migration_Total,Deaths_Total,Deaths_At_Birth,Deaths_Ages_0_4,Population_Density_Total,Population,...,World_Region,Population_Type,Population_Net_Change,GDP_Per_Capita_PPP,GDP_Per_Capita_Constant,Price_Level_Ratio,GDP_Capita_Group_PPP,Date,Sub_Region,geojson_string
13064,Russia,RUS,1989,2205133.0,89400.0,1573505.0,38493.0,48729.0,9.055,148281862.0,...,Europe,3. Large (100M-250M),721028.0,NaN,NaN,NaN,Высокий,1989-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13065,Russia,RUS,1990,2026802.0,299863.0,1652347.0,34468.0,43960.0,9.098,148979537.0,...,Europe,3. Large (100M-250M),674318.0,18734.559499,7796.296537,2.403008,Высокий,1990-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13066,Russia,RUS,1991,1832068.0,125505.0,1694109.0,31545.0,40768.0,9.126,149448433.0,...,Europe,3. Large (100M-250M),263464.0,18360.816470,7379.595741,2.488052,Высокий,1991-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13067,Russia,RUS,1992,1621382.0,-1129589.0,1820134.0,28194.0,36786.0,9.094,148915993.0,...,Europe,3. Large (100M-250M),-1328341.0,17040.783860,6329.812465,2.692147,Высокий,1992-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13068,Russia,RUS,1993,1416115.0,507229.0,2156133.0,27417.0,36028.0,9.046,148135419.0,...,Europe,3. Large (100M-250M),-232789.0,14759.262267,5811.572679,2.539633,Высокий,1993-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13069,Russia,RUS,1994,1420437.0,1271417.0,2328453.0,26535.0,34082.0,9.050,148200734.0,...,Europe,3. Large (100M-250M),363401.0,12484.341845,5078.832846,2.458112,Высокий,1994-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13070,Russia,RUS,1995,1388504.0,723875.0,2294449.0,24892.0,32148.0,9.056,148291406.0,...,Europe,3. Large (100M-250M),-182070.0,11653.427340,4865.413213,2.395157,Высокий,1995-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13071,Russia,RUS,1996,1333368.0,587171.0,2152108.0,23078.0,29052.0,9.043,148084580.0,...,Europe,3. Large (100M-250M),-231569.0,11414.416005,4689.253796,2.434165,Высокий,1996-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13072,Russia,RUS,1997,1294194.0,541387.0,2065644.0,21884.0,27592.0,9.029,147853769.0,...,Europe,3. Large (100M-250M),-230063.0,11056.993244,4762.322161,2.321765,Высокий,1997-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13073,Russia,RUS,1998,1302572.0,528135.0,2037123.0,21576.0,26712.0,9.016,147635543.0,...,Europe,3. Large (100M-250M),-206416.0,10013.361925,4516.587209,2.217020,Высокий,1998-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13074,Russia,RUS,1999,1251222.0,375468.0,2207394.0,20790.0,26284.0,8.992,147241973.0,...,Europe,3. Large (100M-250M),-580704.0,9616.628643,4818.490172,1.995776,Высокий,1999-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13075,Russia,RUS,2000,1268072.0,550401.0,2286159.0,19838.0,24935.0,8.959,146717784.0,...,Europe,3. Large (100M-250M),-467686.0,10951.593298,5319.279316,2.058849,Высокий,2000-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13076,Russia,RUS,2001,1315495.0,259614.0,2308425.0,19713.0,24605.0,8.923,146117290.0,...,Europe,3. Large (100M-250M),-733316.0,11295.621654,5613.540671,2.012210,Высокий,2001-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13077,Russia,RUS,2002,1403587.0,1358944.0,2384782.0,19474.0,23786.0,8.912,145939502.0,...,Europe,3. Large (100M-250M),377749.0,11589.494118,5884.536629,1.969483,Высокий,2002-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13078,Russia,RUS,2003,1486835.0,256804.0,2411911.0,18550.0,22701.0,8.903,145794230.0,...,Europe,3. Large (100M-250M),-668272.0,12765.454607,6320.396487,2.019724,Высокий,2003-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13079,Russia,RUS,2004,1513809.0,261519.0,2335314.0,17730.0,21751.0,8.866,145180091.0,...,Europe,3. Large (100M-250M),-559986.0,14462.642471,6804.123213,2.125570,Высокий,2004-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13080,Russia,RUS,2005,1472805.0,263541.0,2340784.0,16141.0,20307.0,8.830,144597886.0,...,Europe,3. Large (100M-250M),-604438.0,16687.984290,7268.734015,2.295858,Высокий,2005-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13081,Russia,RUS,2006,1499536.0,308370.0,2193337.0,15535.0,19526.0,8.800,144102948.0,...,Europe,3. Large (100M-250M),-385431.0,19618.299204,7891.787632,2.485913,Высокий,2006-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13082,Russia,RUS,2007,1632575.0,365717.0,2099223.0,15778.0,19418.0,8.785,143859767.0,...,Europe,3. Large (100M-250M),-100931.0,23139.117138,8577.062051,2.697791,Высокий,2007-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13083,Russia,RUS,2008,1739291.0,360840.0,2095041.0,14997.0,18469.0,8.782,143811837.0,...,Europe,3. Large (100M-250M),5090.0,26633.843777,9026.073874,2.950767,Высокий,2008-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13084,Russia,RUS,2009,1788518.0,350206.0,2029235.0,14747.0,18067.0,8.786,143869128.0,...,Europe,3. Large (100M-250M),109489.0,23761.042744,8318.726691,2.856332,Высокий,2009-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13085,Russia,RUS,2010,1815200.0,307555.0,2101577.0,15212.0,20840.0,8.790,143934468.0,...,Europe,3. Large (100M-250M),21178.0,27010.121717,8689.123116,3.108498,Высокий,2010-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13086,Russia,RUS,2011,1824538.0,309377.0,1936517.0,13862.0,17204.0,8.796,144043751.0,...,Europe,3. Large (100M-250M),197398.0,30890.149480,9055.882220,3.411059,Высокий,2011-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13087,Russia,RUS,2012,1928586.0,285977.0,1917404.0,16890.0,20249.0,8.811,144291025.0,...,Europe,3. Large (100M-250M),297159.0,33286.997580,9404.154995,3.539605,Высокий,2012-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13088,Russia,RUS,2013,1922462.0,289872.0,1883361.0,15676.0,18793.0,8.830,144604105.0,...,Europe,3. Large (100M-250M),328973.0,32592.179869,9548.519414,3.413323,Высокий,2013-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13089,Russia,RUS,2014,1939723.0,264698.0,1890305.0,14359.0,17523.0,8.850,144925639.0,...,Europe,3. Large (100M-250M),314116.0,31174.508052,9597.481583,3.248197,Высокий,2014-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13090,Russia,RUS,2015,1934705.0,384756.0,1869623.0,12693.0,15533.0,8.873,145307612.0,...,Europe,3. Large (100M-250M),449838.0,27982.737408,9383.418827,2.982147,Высокий,2015-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13091,Russia,RUS,2016,1886740.0,447645.0,1842111.0,11286.0,13999.0,8.902,145778668.0,...,Europe,3. Large (100M-250M),492274.0,27897.015426,9371.214119,2.976884,Высокий,2016-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13092,Russia,RUS,2017,1695524.0,396619.0,1768167.0,9206.0,11723.0,8.927,146186798.0,...,Europe,3. Large (100M-250M),323976.0,29584.966352,9515.672214,3.109078,Высокий,2017-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13093,Russia,RUS,2018,1612827.0,339972.0,1790070.0,8120.0,10430.0,8.942,146430146.0,...,Europe,3. Large (100M-250M),162729.0,31308.337970,9766.542734,3.205673,Высокий,2018-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13094,Russia,RUS,2019,1496027.0,336494.0,1789415.0,7175.0,9251.0,8.948,146533063.0,...,Europe,3. Large (100M-250M),43106.0,34203.806277,9974.208463,3.429225,Высокий,2019-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13095,Russia,RUS,2020,1458020.0,334094.0,2158768.0,6732.0,8660.0,8.938,146371295.0,...,Europe,3. Large (100M-250M),-366654.0,34294.353958,9720.258298,3.528132,Высокий,2020-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13096,Russia,RUS,2021,1421809.0,314112.0,2439514.0,6372.0,8445.0,8.906,145836172.0,...,Europe,3. Large (100M-250M),-703593.0,37815.803339,10328.255817,3.661393,Высокий,2021-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13097,Russia,RUS,2022,1334912.0,765629.0,1909498.0,5237.0,6816.0,8.890,145579889.0,...,Europe,3. Large (100M-250M),191043.0,37209.030294,10197.875319,3.648704,Высокий,2022-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13098,Russia,RUS,2023,1297207.0,27807.0,1794858.0,4617.0,5935.0,8.882,145440502.0,...,Europe,3. Large (100M-250M),-469844.0,39226.796673,10624.378532,3.692150,Высокий,2023-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."
13099,Russia,RUS,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Europe,3. Large (100M-250M),NaN,NaN,NaN,3.538427,Высокий,2024-01-01,Eastern Europe,"{""type"": ""MultiPolygon"", ""coordinates"": [[[[87..."

In [101]:
df_final.to_csv(r"G:\Демография\prepared_data.csv", index=False, encoding='utf-8-sig')